In [9]:
import numpy as np
X=np.sort(5*np.random.rand(40,1),axis=0)
X

array([[0.05984589],
       [0.21560695],
       [0.24802834],
       [0.27542578],
       [0.2963458 ],
       [0.41690121],
       [0.42556784],
       [0.4343907 ],
       [0.89982513],
       [1.0786179 ],
       [1.10380882],
       [1.24938763],
       [1.28323358],
       [1.57604607],
       [1.75631203],
       [1.91583118],
       [2.01256404],
       [2.22544397],
       [2.25968216],
       [2.30818358],
       [2.41178155],
       [2.4515648 ],
       [2.50232143],
       [2.68021588],
       [2.90318392],
       [3.04356873],
       [3.10466034],
       [3.13969367],
       [3.19522414],
       [3.23086035],
       [3.64938974],
       [3.75367324],
       [3.83625331],
       [4.12939429],
       [4.13565913],
       [4.34052465],
       [4.62397301],
       [4.65822361],
       [4.93734264],
       [4.9670871 ]])

In [14]:
y=np.ravel(2*X + 3)
y

array([ 3.11969178,  3.4312139 ,  3.49605668,  3.55085155,  3.5926916 ,
        3.83380243,  3.85113568,  3.8687814 ,  4.79965026,  5.15723579,
        5.20761765,  5.49877527,  5.56646715,  6.15209215,  6.51262405,
        6.83166237,  7.02512808,  7.45088794,  7.51936432,  7.61636716,
        7.8235631 ,  7.9031296 ,  8.00464285,  8.36043175,  8.80636784,
        9.08713745,  9.20932069,  9.27938733,  9.39044828,  9.46172071,
       10.29877949, 10.50734648, 10.67250662, 11.25878857, 11.27131827,
       11.68104931, 12.24794601, 12.31644721, 12.87468527, 12.93417419])

In [13]:
y[::5]

array([ 3.11969178,  3.83380243,  5.20761765,  6.83166237,  7.8235631 ,
        9.08713745, 10.29877949, 11.68104931])